# This file is used by Docker Compose to define and run the containers for 
# the demo application. The containers include a Redis server, a Celery worker, 
# and a FastAPI server.

version: '3'
services:
  backend_redis:
    image: "redis:alpine"
    container_name: backend_redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - backend_network
  
  backend_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend_redis
    command: ["bash", "-c", "sh start_celery.sh"]
    networks:
      - backend_network
  
  backend_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    
    restart: unless-stopped
    command: ["bash", "-c", "sh start_gunicorn.sh"]
    networks:
      - backend_network


networks:
  backend_network:
    driver: bridge